<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="6">
            <File firstVisibleLine="1074" xOffset="0" scrollWidth="287668" startPos="0" endPos="3" selMode="0" lang="Normal Text" encoding="-1" filename="D:\Games\Hellblade Senuas Sacrifice\Engine\Binaries\ThirdParty\Steamworks\Steamv132\Win64\steam_api64.dll" backupFilePath="" originalFileLastModifTimestamp="554915712" originalFileLastModifTimestampHigh="30609403" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="945" startPos="920" endPos="920" selMode="0" lang="JavaScript" encoding="-1" filename="D:\Chat con socket.io\index.js" backupFilePath="" originalFileLastModifTimestamp="1125843248" originalFileLastModifTimestampHigh="30724221" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="7274574" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="513" startPos="44" endPos="44" selMode="0" lang="JavaScript" encoding="-1" filename="C:\FrontVistaNueva-master\src\Configuracion\Config.js" backupFilePath="C:\Users\alex2\AppData\Roaming\Notepad++\backup\Config.js@2019-09-12_175848" originalFileLastModifTimestamp="1443270784" originalFileLastModifTimestampHigh="30689771" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="891" startPos="155" endPos="155" selMode="0" lang="YAML" encoding="-1" filename="C:\ModuloAlumnoJDBC-master\src\main\resources\application.yml" backupFilePath="" originalFileLastModifTimestamp="1613901404" originalFileLastModifTimestampHigh="30767677" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="0" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="6120" startPos="70" endPos="70" selMode="0" lang="Normal Text" encoding="1252" filename="C:\ModuloAlumnoJDBC-master\target\classes\edu\moduloalumno\model\ConceptoJSON.class" backupFilePath="" originalFileLastModifTimestamp="-442959487" originalFileLastModifTimestampHigh="30762396" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="643573968" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1746" startPos="0" endPos="0" selMode="0" lang="Java" encoding="-1" filename="C:\sigapdev-consultarecibos-back-master\src\main\java\edu\moduloalumno\entity\Recaudaciones.java" backupFilePath="" originalFileLastModifTimestamp="1608727040" originalFileLastModifTimestampHigh="30771885" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="1819626042" mapWrapIndentMode="-1" mapIsWrap="no" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="666" startPos="38" endPos="38" selMode="0" lang="JavaScript" encoding="-1" filename="C:\sigapdev-consultarecibos-front-master\src\Configuracion\Config.js" backupFilePath="C:\Users\alex2\AppData\Roaming\Notepad++\backup\Config.js@2019-11-25_220114" originalFileLastModifTimestamp="1633628928" originalFileLastModifTimestampHigh="30771882" mapFirstVisibleDisplayLine="-1" mapFirstVisibleDocLine="-1" mapLastVisibleDocLine="-1" mapNbLine="-1" mapHigherPos="-1" mapWidth="-1" mapHeight="-1" mapKByteInDoc="538970378" mapWrapIndentMode="-1" mapIsWrap="no" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
